apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "elmusty.net@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "ovehqpxxzjwncxbo"
type: Opaque

# Passw0rd@1234